apiVersion: secrets-store.csi.x-k8s.io/v1 #secrets-store.csi.x-k8s.io/v1alpha1 #secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.provider }}
  namespace: {{ .Values.labels.namespace }}
spec:
  provider: aws          

  secretObjects:
  - secretName: {{ .Values.secrets.name }}
    type: Opaque
    data:
    - objectName: dbusername
      key: db_username
    - objectName: dbpassword
      key: db_password
    - objectName: dburl
      key: db_url
    - objectName: databaseurl
      key: database_url
    - objectName: appsecrets
      key: app_secrets
  parameters:
    objects: |
      - objectName: {{ .Values.secrets.secretname }}
        objectType: secretsmanager
        objectAlias: appsecrets
        jmesPath: 
            - path: ("DB_USERNAME")
              objectAlias: dbusername
            - path: ("DB_PASSWORD")
              objectAlias: dbpassword
            - path: ("DB_URL")
              objectAlias: dburl
            - path: ("DATABASE_URL")
              objectAlias: databaseurl
    
  
