version: "3.3"
services:
  bp-client:
    container_name: bp-client
    build:
      context: ../quickstart-template-angular-helloworld-client/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    #Uncomment if you want use React and also comment Line 5-9
    #    build:
    #      context: ../quickstart-template-reactjs-helloworld-client/
    #      dockerfile: Dockerfile
    #      ports:
    #        - "3000:3000"
    volumes:
      - ../quickstart-template-angular-helloworld-client:/app
      - /app/node_modules

  bp-service-db:
    image: mongo:4.0
    container_name: bp-service-db
    ports:
      - 27019:27017
    volumes:
      - bp-service-db-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  bp-service:
    container_name: bp-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - bp-service-db
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: bp-service-db:27017
      SPRING_DATA_MONGODB_URI: mongodb://bp-service-db/QuickstartBlueprint
      CORS_URL: http://localhost:4200
      USER_POOL_ID: us-east-1_3zlTNEEt1
      OAUTH_IDP_HOST: https://dev-cqs-blueprint-test.auth.us-east-1.amazoncognito.com/
      OAUTH_IDP_CLIENT_ID: 1ef5gt0u209ri742o9vb19amb3
      OAUTH_REDIRECTURI: http://localhost:4200
      OAUTH_CLIENT_APP_HOST: http://localhost:4200
      OAUTH_IDP_ISSUER: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_3zlTNEEt1
      OAUTH_IDP_AUTH_END_POINT: https://dev-cqs-blueprint-test.auth.us-east-1.amazoncognito.com/oauth2/authorize
      OAUTH_IDP_TOKEN_END_POINT: https://dev-cqs-blueprint-test.auth.us-east-1.amazoncognito.com/oauth2/token
      OAUTH_IDP_END_SESSION_END_POINT: https://dev-cqs-blueprint-test.auth.us-east-1.amazoncognito.com/logout?client_id=1ef5gt0u209ri742o9vb19amb3&logout_uri=
      PORT: 8080
      STUDIO_APP_ENV: development

volumes:
  bp-service-db-volume:
